server:
  servlet:
    context-path: /accost
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://wangyl97.mysql.rds.aliyuncs.com/db_location?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: wangyl
    password: a1B2c3D4
  rabbitmq:
    host: 150.158.185.208
    username: guest
    password: guest
  application:
    name: ACCOST
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://150.158.185.208:8080/eureka
  instance:
    prefer-ip-address: true
