eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
spring:
  application:
    name: EUREKA
  cloud:
    loadbalancer:
      ribbon:
        enabled: false